HW2 done
Glebeeezy/Homework-.NET-2023- pull request #1
Opened 2023-09-09 22:32 UTC by Glebeeezy

2023-09-27 08:15 UTC, HolubVasy requested changes

2023-09-27 08:15 UTC, HolubVasy commented on Homework2/Program.cs
> +            char[] Link5(int number)
!Comment
Also use **descriptive** variable and function **names**. Avoid names like `Link5` which don't convey the purpose of the function.

2023-09-27 08:15 UTC, HolubVasy commented on Homework2/Program.cs
> +                char[] secondChArr = secondStrRev.ToCharArray();
!Recommendation
Can be simplified by removing these two lines.

2023-09-27 08:15 UTC, HolubVasy commented on Homework2/Program.cs
> +            string[] mySplit(string str)
!Comment
Use comments to briefly explain the purpose of each function.   This will help others (and yourself, in the future in the production) to understand what each function does without having to dive deep into its implementation.

2023-09-27 09:36 UTC, HolubVasy requested changes

2023-11-11 21:17 UTC, VasiliHolubITAcademy2023 approved these changes

2023-11-11 21:18 UTC, merged