Tank factory
Glebeeezy/Homework-.NET-2023- pull request #3
Opened 2023-09-24 14:13 UTC by Glebeeezy

Homework done.

2023-09-27 09:51 UTC, HolubVasy requested changes

2023-09-27 09:51 UTC, HolubVasy commented on TankFactory/Contracts/TankBase.cs
> +            if (_engineIsRunning == true)
_!Comment_

### Code concise

`== true` can be safely removed.

2023-09-27 09:51 UTC, HolubVasy commented on TankFactory/Realisations/HeavyTank.cs
> +            if (_engineIsRunning == true)
_!Comment_

### Code concise

`== true` can be safely removed.

2023-09-27 09:51 UTC, HolubVasy commented on TankFactory/Realisations/HeavyTank.cs
> +                    }
_!Comment_

### Code concise

`== true` can be safely removed.

2023-09-27 09:51 UTC, HolubVasy commented on TankFactory/Realisations/LightTank.cs
> +                        Y = Y + _speed;
_!Recommendation_

### DRY

Consider creation of private method for repeated logic and reuse it.

```
for (int i = 0; i < timeOfMoivng; i++)
{
    X = X + _speed;
}
StopMoving();
```

2023-09-27 09:51 UTC, HolubVasy commented on TankFactory/Realisations/MediumTank.cs
> +                    StopMoving();
_!Recommendation_

### DRY

Consider creation of private method for repeated logic and reuse it.

```
for (int i = 0; i < timeOfMoivng; i++)
{
    X = X + _speed;
}
StopMoving();
```

part.

2023-11-11 21:55 UTC, VasiliHolubITAcademy2023 approved these changes

2023-11-11 21:55 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Contracts/TankBase.cs
> +        protected bool _engineIsRunning = false;
Default value for bool is false

2023-11-11 21:55 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Contracts/TankBase.cs
> +        protected bool _isMoving = false;
Default value for bool is false. '= false' can be safely removed

2023-11-11 21:55 UTC, merged

2023-11-11 22:10 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Realisations/HeavyTank.cs
> +            for (int i = 0; i < timeOfMoving; i++)
Can be converted into `Enumerable.Range(0,  timeOfMoving  )` for using foreach construction

2023-11-11 22:10 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Realisations/LightTank.cs
> +            if (_engineIsRunning)
Try using switch construction

2023-11-11 22:10 UTC, VasiliHolubITAcademy2023 commented on TankFactory/StaticFabric/TankFabric.cs
> +            else
Extract validation and code guard in the start of method for conciseness 

```
if ( string.IsNullOrEmpty ( typeType )  )
{
      Console.WriteLine("Указан неверный тип танка");
      return null;
}

```

2023-11-11 22:10 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Contracts/TankBase.cs
> +            get { return _x; }
Can be safely converted in to auto-property as `_x` is not used directly

2023-11-11 22:10 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Contracts/TankBase.cs
> +        public int Y
Can be safely converted in to auto-property as `_y` is not used directly

2023-11-11 22:10 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Contracts/TankBase.cs
> +                if (_direction == Direction.straight)
Try use switch by occasion

2023-11-11 22:10 UTC, VasiliHolubITAcademy2023 commented on TankFactory/Enums/DirectionsEnum.cs
> +using System.Linq;
Remove not used using expressions